TESTS WITH ERRORS 
test14 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 405, in test14
    KB.kb_retract(fact2)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/student_code.py", line 136, in kb_retract
    self.kb_remove(current)
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/student_code.py", line 153, in kb_remove
    index = x.supported_by.index(fact_rule)
ValueError: Fact('fact', Statement('healthGoesTo', [Term(Constant('A'))]), False, [], [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [], [], []), Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [Fact('fact', Statement('healthGoesTo', [Term(Constant('A'))]), False, [], [...], []), Rule('rule', [Statement('healthGoesTo', [Term(Constant('A'))])], Statement('heathyPerson', [Term(Constant('A'))]), False, [Fact('fact', Statement('person', [Term(Constant('A'))]), False, [], [], [Rule('rule', [Statement('healthGoesTo', [Term(Constant('A'))])], Statement('heathyPerson', [Term(Constant('A'))]), False, [], [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [], [], [])], []), Rule('rule', [Statement('healthGoesTo', [Term(Constant('A'))])], Statement('heathyPerson', [Term(Constant('A'))]), False, [...], [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [...], [], [])], [])]), Rule('rule', [Statement('person', [Term(Variable('?x'))]), Statement('healthGoesTo', [Term(Variable('?x'))])], Statement('heathyPerson', [Term(Variable('?x'))]), True, [], [], [Rule('rule', [Statement('healthGoesTo', [Term(Constant('A'))])], Statement('heathyPerson', [Term(Constant('A'))]), False, [], [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [], [], [])], []), Rule('rule', [Statement('healthGoesTo', [Term(Constant('A'))])], Statement('heathyPerson', [Term(Constant('A'))]), False, [...], [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [...], [], [])], [])])], [Fact('fact', Statement('heathyPerson', [Term(Constant('A'))]), False, [...], [], [])], [])], [], [])], []) is not in list

-------------------------------
TESTS FAILED  
test5 (gradingtests.UnitTests)
Traceback (most recent call last):
  File "/Users/k2i/academics/automatedgradingapp/app/testing/kb-inference/gradingtests.py", line 151, in test5
    self.assertTrue(len(answer4) > 0)
AssertionError: False is not true

-------------------------------
TESTS SKIPPED 
-------------------------------
